version: "3.9"

services:
  dagster:
    build: .
    container_name: radar_dagster
    restart: always
    ports:
      - "3000:3000"
    environment:
      - FRANCE_TRAVAIL_CLIENT_ID=${FRANCE_TRAVAIL_CLIENT_ID}
      - FRANCE_TRAVAIL_SECRET_KEY=${FRANCE_TRAVAIL_SECRET_KEY}
    volumes:
      - ./dbt_project:/app/dbt_project
      - ./data:/app/data
      - ./dagster_home:/app/dagster_home
    # La commande exacte qui fonctionne chez toi :
    command: ["dagster", "dev", "-f", "dagster/repository.py", "--host", "0.0.0.0", "--port", "3000"]